import { defineConfig } from 'vitest/config';
import path from 'path';

export default defineConfig({
  test: {
    globals: true,
    testTimeout: 30000,
  },
  resolve: {
    alias: {
      '@adorable/core': path.resolve(__dirname, '../packages/core/src/index.ts'),
      '@adorable/schema': path.resolve(__dirname, '../packages/schema/src/index.ts'),
      '@adorable/plugin-api': path.resolve(__dirname, '../packages/plugin-api/src/index.ts'),
      '@adorable/observability': path.resolve(__dirname, '../packages/observability/src/index.ts'),
      '@adorable/graph-db': path.resolve(__dirname, '../packages/graph-db/src/index.ts'),
      '@adorable/lang-ts': path.resolve(__dirname, '../packages/lang-ts/src/index.ts'),
      '@adorable/framework-prisma': path.resolve(__dirname, '../packages/framework-prisma/src/index.ts'),
      '@adorable/framework-react': path.resolve(__dirname, '../packages/framework-react/src/index.ts'),
      '@adorable/framework-express': path.resolve(__dirname, '../packages/framework-express/src/index.ts'),
      '@adorable/framework-fetch': path.resolve(__dirname, '../packages/framework-fetch/src/index.ts'),
      '@adorable/flow-stitcher': path.resolve(__dirname, '../packages/flow-stitcher/src/index.ts'),
      '@adorable/cli': path.resolve(__dirname, '../packages/cli/src/index.ts'),
      '@adorable/lang-go': path.resolve(__dirname, '../packages/lang-go/src/index.ts'),
      '@adorable/lang-java': path.resolve(__dirname, '../packages/lang-java/src/index.ts'),
      '@adorable/lang-php': path.resolve(__dirname, '../packages/lang-php/src/index.ts'),
      '@adorable/lang-rust': path.resolve(__dirname, '../packages/lang-rust/src/index.ts'),
      '@adorable/lang-py': path.resolve(__dirname, '../packages/lang-py/src/index.ts'),
      '@adorable/framework-gin': path.resolve(__dirname, '../packages/framework-gin/src/index.ts'),
      '@adorable/framework-gohttp': path.resolve(__dirname, '../packages/framework-gohttp/src/index.ts'),
      '@adorable/framework-actix': path.resolve(__dirname, '../packages/framework-actix/src/index.ts'),
      '@adorable/framework-axum': path.resolve(__dirname, '../packages/framework-axum/src/index.ts'),
      '@adorable/framework-rocket': path.resolve(__dirname, '../packages/framework-rocket/src/index.ts'),
      '@adorable/framework-spring': path.resolve(__dirname, '../packages/framework-spring/src/index.ts'),
      '@adorable/framework-jpa': path.resolve(__dirname, '../packages/framework-jpa/src/index.ts'),
      '@adorable/framework-gorm': path.resolve(__dirname, '../packages/framework-gorm/src/index.ts'),
      '@adorable/framework-laravel': path.resolve(__dirname, '../packages/framework-laravel/src/index.ts'),
      '@adorable/framework-pycli': path.resolve(__dirname, '../packages/framework-pycli/src/index.ts'),
      '@adorable/framework-gocli': path.resolve(__dirname, '../packages/framework-gocli/src/index.ts'),
      '@adorable/framework-rustcli': path.resolve(__dirname, '../packages/framework-rustcli/src/index.ts'),
      '@adorable/framework-fastify': path.resolve(__dirname, '../packages/framework-fastify/src/index.ts'),
      '@adorable/framework-nestjs': path.resolve(__dirname, '../packages/framework-nestjs/src/index.ts'),
      '@adorable/framework-nextjs': path.resolve(__dirname, '../packages/framework-nextjs/src/index.ts'),
      '@adorable/framework-axios': path.resolve(__dirname, '../packages/framework-axios/src/index.ts'),
      '@adorable/framework-supabase': path.resolve(__dirname, '../packages/framework-supabase/src/index.ts'),
      '@adorable/framework-typeorm': path.resolve(__dirname, '../packages/framework-typeorm/src/index.ts'),
      '@adorable/framework-mongoose': path.resolve(__dirname, '../packages/framework-mongoose/src/index.ts'),
      '@adorable/framework-fastapi': path.resolve(__dirname, '../packages/framework-fastapi/src/index.ts'),
      '@adorable/framework-sqlalchemy': path.resolve(__dirname, '../packages/framework-sqlalchemy/src/index.ts'),
      '@adorable/framework-django': path.resolve(__dirname, '../packages/framework-django/src/index.ts'),
      '@adorable/framework-flask': path.resolve(__dirname, '../packages/framework-flask/src/index.ts'),
      '@adorable/framework-trpc': path.resolve(__dirname, '../packages/framework-trpc/src/index.ts'),
      '@adorable/framework-graphql': path.resolve(__dirname, '../packages/framework-graphql/src/index.ts'),
      '@adorable/framework-vue': path.resolve(__dirname, '../packages/framework-vue/src/index.ts'),
      '@adorable/framework-koa': path.resolve(__dirname, '../packages/framework-koa/src/index.ts'),
      '@adorable/framework-hapi': path.resolve(__dirname, '../packages/framework-hapi/src/index.ts'),
      '@adorable/framework-hono': path.resolve(__dirname, '../packages/framework-hono/src/index.ts'),
      '@adorable/framework-remix': path.resolve(__dirname, '../packages/framework-remix/src/index.ts'),
      '@adorable/framework-angular': path.resolve(__dirname, '../packages/framework-angular/src/index.ts'),
      '@adorable/framework-svelte': path.resolve(__dirname, '../packages/framework-svelte/src/index.ts'),
      '@adorable/framework-state-mgmt': path.resolve(__dirname, '../packages/framework-state-mgmt/src/index.ts'),
      '@adorable/mcp-server': path.resolve(__dirname, '../packages/mcp-server/src/index.ts'),
    },
  },
});
