import { defineConfig } from 'vitest/config';
import path from 'path';

export default defineConfig({
  test: {
    globals: true,
    testTimeout: 60000,
    include: ['**/*.test.ts'],
  },
  resolve: {
    alias: {
      '@veoable/schema': path.resolve(__dirname, '../../packages/schema/src/index.ts'),
      '@veoable/plugin-api': path.resolve(__dirname, '../../packages/plugin-api/src/index.ts'),
      '@veoable/observability': path.resolve(__dirname, '../../packages/observability/src/index.ts'),
      '@veoable/graph-db': path.resolve(__dirname, '../../packages/graph-db/src/index.ts'),
      '@veoable/lang-ts': path.resolve(__dirname, '../../packages/lang-ts/src/index.ts'),
      '@veoable/lang-py': path.resolve(__dirname, '../../packages/lang-py/src/index.ts'),
      '@veoable/lang-go': path.resolve(__dirname, '../../packages/lang-go/src/index.ts'),
      '@veoable/lang-java': path.resolve(__dirname, '../../packages/lang-java/src/index.ts'),
      '@veoable/lang-php': path.resolve(__dirname, '../../packages/lang-php/src/index.ts'),
      '@veoable/lang-rust': path.resolve(__dirname, '../../packages/lang-rust/src/index.ts'),
      '@veoable/cli': path.resolve(__dirname, '../../packages/cli/src/index.ts'),
      '@veoable/flow-stitcher': path.resolve(__dirname, '../../packages/flow-stitcher/src/index.ts'),
      '@veoable/framework-express': path.resolve(__dirname, '../../packages/framework-express/src/index.ts'),
      '@veoable/framework-fastify': path.resolve(__dirname, '../../packages/framework-fastify/src/index.ts'),
      '@veoable/framework-nestjs': path.resolve(__dirname, '../../packages/framework-nestjs/src/index.ts'),
      '@veoable/framework-nextjs': path.resolve(__dirname, '../../packages/framework-nextjs/src/index.ts'),
      '@veoable/framework-koa': path.resolve(__dirname, '../../packages/framework-koa/src/index.ts'),
      '@veoable/framework-hapi': path.resolve(__dirname, '../../packages/framework-hapi/src/index.ts'),
      '@veoable/framework-hono': path.resolve(__dirname, '../../packages/framework-hono/src/index.ts'),
      '@veoable/framework-remix': path.resolve(__dirname, '../../packages/framework-remix/src/index.ts'),
      '@veoable/framework-fastapi': path.resolve(__dirname, '../../packages/framework-fastapi/src/index.ts'),
      '@veoable/framework-flask': path.resolve(__dirname, '../../packages/framework-flask/src/index.ts'),
      '@veoable/framework-django': path.resolve(__dirname, '../../packages/framework-django/src/index.ts'),
      '@veoable/framework-gin': path.resolve(__dirname, '../../packages/framework-gin/src/index.ts'),
      '@veoable/framework-gohttp': path.resolve(__dirname, '../../packages/framework-gohttp/src/index.ts'),
      '@veoable/framework-actix': path.resolve(__dirname, '../../packages/framework-actix/src/index.ts'),
      '@veoable/framework-axum': path.resolve(__dirname, '../../packages/framework-axum/src/index.ts'),
      '@veoable/framework-rocket': path.resolve(__dirname, '../../packages/framework-rocket/src/index.ts'),
      '@veoable/framework-spring': path.resolve(__dirname, '../../packages/framework-spring/src/index.ts'),
      '@veoable/framework-laravel': path.resolve(__dirname, '../../packages/framework-laravel/src/index.ts'),
      '@veoable/framework-trpc': path.resolve(__dirname, '../../packages/framework-trpc/src/index.ts'),
      '@veoable/framework-graphql': path.resolve(__dirname, '../../packages/framework-graphql/src/index.ts'),
      '@veoable/framework-vue': path.resolve(__dirname, '../../packages/framework-vue/src/index.ts'),
      '@veoable/framework-react': path.resolve(__dirname, '../../packages/framework-react/src/index.ts'),
      '@veoable/framework-fetch': path.resolve(__dirname, '../../packages/framework-fetch/src/index.ts'),
      '@veoable/framework-axios': path.resolve(__dirname, '../../packages/framework-axios/src/index.ts'),
      '@veoable/framework-prisma': path.resolve(__dirname, '../../packages/framework-prisma/src/index.ts'),
      '@veoable/framework-mongoose': path.resolve(__dirname, '../../packages/framework-mongoose/src/index.ts'),
      '@veoable/framework-typeorm': path.resolve(__dirname, '../../packages/framework-typeorm/src/index.ts'),
      '@veoable/framework-supabase': path.resolve(__dirname, '../../packages/framework-supabase/src/index.ts'),
      '@veoable/framework-sqlalchemy': path.resolve(__dirname, '../../packages/framework-sqlalchemy/src/index.ts'),
      '@veoable/framework-state-mgmt': path.resolve(__dirname, '../../packages/framework-state-mgmt/src/index.ts'),
      '@veoable/framework-angular': path.resolve(__dirname, '../../packages/framework-angular/src/index.ts'),
      '@veoable/framework-svelte': path.resolve(__dirname, '../../packages/framework-svelte/src/index.ts'),
      '@veoable/framework-hono': path.resolve(__dirname, '../../packages/framework-hono/src/index.ts'),
      '@veoable/framework-remix': path.resolve(__dirname, '../../packages/framework-remix/src/index.ts'),
      '@veoable/framework-jpa': path.resolve(__dirname, '../../packages/framework-jpa/src/index.ts'),
      '@veoable/framework-gorm': path.resolve(__dirname, '../../packages/framework-gorm/src/index.ts'),
      '@veoable/framework-pycli': path.resolve(__dirname, '../../packages/framework-pycli/src/index.ts'),
      '@veoable/framework-gocli': path.resolve(__dirname, '../../packages/framework-gocli/src/index.ts'),
      '@veoable/framework-rustcli': path.resolve(__dirname, '../../packages/framework-rustcli/src/index.ts'),
      '@veoable/mcp-server': path.resolve(__dirname, '../../packages/mcp-server/src/index.ts'),
    },
  },
});
